app/Http/routes.php
<?php

Route::resource('Usuario','UsuarioController');
Route::resource('Cliente','ClienteController');
Route::Controller("Cliente","ClienteController");
Route::resource('Vehiculo','VehiculoController');
Route::resource('Lavado','LavadoController');
Route::resource('Comprobante','ComprobanteController');
Route::resource('log','LogController');
Route::get('logout','LogController@logout');
Route::resource('Buscar','GananciaController');
Route::resource('MejorLavador','MejorLavadorController');
Route::resource('MejorAuto','AutoController');

////Route::post('/Cliente/show', 'ClienteController@store');

Route::Controller("/Cliente","ClienteController");
Route::Controller("/Usuario","UsuarioController");









/**ESTO SON DEL MENU QUE NOS EMPEZARA A MOSTRAR ¨*/
Route::get('/','FrontController@index');
Route::get('contacto','FrontController@contacto');
Route::get('reviews','FrontController@reviews');


Route::get('admin','FrontController@admin');
Route:: get('index','FrontController@index');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');*/

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Http/Controllers/UsuarioController.php
<?php namespace CarWash\Http\Controllers;

use CarWash\Http\Requests;
use CarWash\Http\Requests\UserCreateRequest;
use CarWash\Http\Controllers\Controller;
use CarWash\User;
use Session;
use Redirect;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use CarWash\Lavado;

class UsuarioController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */

	public function __construct(){
		$this->middleware('auth');
		$this->middleware('admin');
        $this->beforeFilter('@find',['only' => ['edit','update','destroy']]);
    }

    public function find(Route $route){
        $this->user = User::find($route->getParameter('Usuario'));
    }


	public function index()
	{
		$users = User:: paginate(3);
		return view('usuario.index',compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('usuario.create');

	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(UserCreateRequest $request)
	{
		    User::create([
		    'dni' => $request['dni'],
            'name' => $request['name'],
            'apellidos' => $request['apellidos'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
            /*'password' => $request['password'],*/
            'estatus' => $request['estatus'],
            'tipo' => $request['tipo'],
        ]);
        Session::flash('message','Usuario Creado Correctamente');
        return Redirect::to('/Usuario');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        return view('usuario.edit',['user'=>$this->user]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
        $this->user->fill($request->all());
        $this->user->save();
        Session::flash('message','Usuario Actualizado Correctamente');
        return Redirect::to('/Usuario');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->user->delete();
        Session::flash('message','Usuario Eliminado Correctamente');
        return Redirect::to('/Usuario');

	}

}

resources/views/usuario/create.blade.php
@extends('layouts.admin')
	@section('content')
	@if(count($errors) > 0)
		<div class="alert alert-danger alert-dismissible" role="alert">
	  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  	<ul>
	  		@foreach($errors->all() as $error)
	  		<li>{!! $error !!}</li>
	  		@endforeach
	  	</ul>
		</div>
	@endif
	
	<div>
	{!!Form::open(['route'=>'Usuario.store', 'method'=>'POST'])!!}
			@include('usuario.forms.usr')
	</div>
	
	<div class="cuadro">
	<table style="  border-collapse: separate; border-spacing: 10px 5px">
		<td>
	{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
	{!!Form::close()!!}
		</td>
		<td>
			<a href="{{URL::to('/Usuario')}}" class="btn btn-success">Regresar</a>
		</td>
	<table>
	@endsection

resources/views/usuario/edit.blade.php
@extends('layouts.admin')
@section('content')
@include('alerts.request')
		
	<br>
	<div>
		{!!Form::model($user,['route'=>['Usuario.update',$user],'method'=>'PUT'])!!}
			@include('usuario.forms.usr')
	</div>
	<div class="cuadro">
	<table style="  border-collapse: separate;
 	 border-spacing: 10px 5px">
		
		<td>
			{!!Form::submit('Actualizar',['class'=>'btn btn-info'])!!}
			{!!Form::close()!!}
		</td>
		
		<td>
		<a href="{{URL::to('/Usuario')}}" class="btn btn-success">Regresar</a>
		</td>
		<!--<td>
			{!!Form::open(['route'=>['Usuario.destroy', $user], 'method' => 'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
			{!!Form::close()!!}

		</td>-->
	</table>
	@endsection

resources/views/usuario/index.blade.php
@extends('layouts.admin')


@include('alerts.success')



	@section('content')
	<table class="table">
		<thead>
			<th>ID</th>
			<th>DNI</th>	
			<th>NOMBRES</th>
			<th>APELLIDOS</th>
			<th>EMAIL</th>
			<th>ESTATUS</th>
			<th>TIPO</th>
			<!--<th>VER</th>-->
			<th>EDITAR</th>
			<th>ELIMINAR</th>
		</thead>
	@foreach($users as $user)
			<tbody>
				<td>{{$user->id}}</td>
				<td>{{$user->dni}}</td>
				<td>{{$user->name}}</td>
				<td>{{$user->apellidos}}</td>
				<td>{{$user->email}}</td>
				<td>{{$user->estatus}}</td>
				<td>{{$user->tipo}}</td>
				<!--<td>
				{!!link_to_route('Usuario.show', $title = 'VER', $parameters = $user->id, $attributes = ['class'=>'btn btn-info'])!!}
				<a href="usuario/show/{{ $user->id}}" class="btn btn-info"> Ver</a>
				</td>-->
				<td>
				{!!link_to_route('Usuario.edit', $title = 'EDITAR', $parameters = $user->id, $attributes = ['class'=>'btn btn-primary'])!!}
				</td>
				<td>
				{!!Form::open(['route'=>['Usuario.destroy', $user], 'method' => 'DELETE'])!!}
				{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
				{!!Form::close()!!}
					</td>
			</tbody>
		@endforeach
	</table>
		{!!$users->render()!!}
	@endsection

resources/views/usuario/show.blade.php
@extends('layouts.admin')


@include('alerts.success')



	@section('content')
	<table class="table">
		<thead>
			<th>ID</th>
			<th>DNI</th>	
			<th>NOMBRES</th>
			<th>APELLIDOS</th>
			<th>EMAIL</th>
			<th>ESTATUS</th>
			<th>TIPO</th>
			<th>VER</th>
			<th>EDITAR</th>
			<th>ELIMINAR</th>
		</thead>
	@foreach($users as $user)
			<tbody>
				<td>{{$user->id}}</td>
				<td>{{$user->dni}}</td>
				<td>{{$user->name}}</td>
				<td>{{$user->apellidos}}</td>
				<td>{{$user->email}}</td>
				<td>{{$user->estatus}}</td>
				<td>{{$user->tipo}}</td>
				<td>
			</tbody>
		@endforeach
	</table>
		{!!$users->render()!!}
	@endsection