app/Http/routes.php
<?php

Route::resource('Usuario','UsuarioController');
Route::resource('Cliente','ClienteController');
Route::Controller("Cliente","ClienteController");
Route::resource('Vehiculo','VehiculoController');
Route::resource('Lavado','LavadoController');
Route::resource('Comprobante','ComprobanteController');
Route::resource('log','LogController');
Route::get('logout','LogController@logout');
Route::resource('Buscar','GananciaController');
Route::resource('MejorLavador','MejorLavadorController');
Route::resource('MejorAuto','AutoController');

////Route::post('/Cliente/show', 'ClienteController@store');

Route::Controller("/Cliente","ClienteController");
Route::Controller("/Usuario","UsuarioController");









/**ESTO SON DEL MENU QUE NOS EMPEZARA A MOSTRAR ¨*/
Route::get('/','FrontController@index');
Route::get('contacto','FrontController@contacto');
Route::get('reviews','FrontController@reviews');


Route::get('admin','FrontController@admin');
Route:: get('index','FrontController@index');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');*/

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Lavado.php
<?php namespace CarWash;

use Illuminate\Database\Eloquent\Model;

class Lavado extends Model {

	protected $table = "lavados";
		/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['dni','tipo','costo','fechaingreso','fechasalida','culminacion','user_id','vehiculo_id'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	///protected $hidden = ['dni','tipo','costo','fechaingreso','fechasalida','culminacion','id_usuario','id_vehiculo'];

	// Relation with Usuario
	public function user()
	{
			return $this->belongsTo(User::class);
			//return $this->belongsTo('User::class');
	}
	//Realacion con Lavado
	public function vehiculo()
	{
			return $this->belongsTo(Vehiculo::class);
			//return $this->belongsTo('Vehiculo::class');
	}

}

app/Http/Controllers/LavadoController.php
<?php namespace CarWash\Http\Controllers;

use CarWash\Http\Requests;
use CarWash\Http\Requests\LavadoCreateRequest;
use CarWash\Http\Requests\LavadoUpdateRequest;
use CarWash\Http\Controllers\Controller;
use CarWash\Lavado;
use Session;
use Redirect;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use CarWash\Vehiculo;
Use CarWash\User;

class LavadoController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */

	public function index(){
		/*$lavados = Lavado::select('lavados.id',
		'lavados.tipo',
		'lavados.costo',
		'lavados.fechaingreso',
		'lavados.fechasalida',
		'lavados.fechaingreso',
		'lavados.culminacion',
		'users.name as lavadousername',
		'vehiculos.placa as lavadoplacavehiculo')
		->join('users','users.id','=','lavados.id_usuario')
		->join('vehiculos','vehiculos.id','=','lavados.id_vehiculo')
		->paginate(5);
		return view('lavado.index',compact('lavados')); */
		
				$lavados = Lavado::all();
							//envia infrmacion con compact
        //return view('lavado.index',compact('lavados'));
		dd($lavados);
			  /// var_dump($lavados);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create(){
		$vehiculo = Vehiculo::lists('placa','id')->prepend('Seleccione Placa del Vehiculo');
    $usuario = User::lists('name','id')->prepend('Seleccione el Nombre del Usuario');
        return view('lavado.create',compact('vehiculo','usuario'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(LavadoCreateRequest $request){
		    Lavado::create([
            'tipo' => $request['tipo'],
            'costo' => $request['costo'],
            'fechaingreso' => $request['fechaingreso'],
            'fechasalida' => $request['fechasalida'],
            'culminacion' => $request['culminacion'],
            'user_id' => $request['id_usuario'],
            'vehiculo_id' => $request['id_vehiculo'],
        ]);
        Session::flash('message','Lavado Creado Correctamente');
        return Redirect::to('/Lavado');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $vehiculo = Vehiculo::lists('placa','id');
        $usuario = 	User::lists('name','id');
        $lavados=	Lavado::find($id);
        //return view('encomienda.edit',['enco'=>$enco]);
        return view('lavado.edit',['lavados'=>$lavados],compact('usuario','vehiculo'));
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(LavadoUpdateRequest $request, $id)
	{
		$lavado =Lavado::find($id);
        $lavado->fill($request->all());
        $lavado->save();
        Session::flash('message','Lavado Actualizado Correctamente');
        return Redirect::to('/Lavado');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$lavado =Lavado::find($id);
        $lavado->delete();
        Session::flash('message','Lavado Eliminado Correctamente');
        return Redirect::to('/Lavado');

	}

}

resources/views/lavado/create.blade.php
@extends('layouts.admin')
	@section('content')
	@if(count($errors) > 0)
		<div class="alert alert-danger alert-dismissible" role="alert">
	  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  	<ul>
	  		@foreach($errors->all() as $error)
	  		<li>{!! $error !!}</li>
	  		@endforeach
	  	</ul>
		</div>
	@endif
	
	<div>
	{!!Form::open(['route'=>'Lavado.store', 'method'=>'POST'])!!}
		@include('lavado.forms.lav')
	</div>
		
		
		<div class="cuadro">
	<table style="  border-collapse: separate; border-spacing: 10px 5px">
		<td>
		{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
		{!!Form::close()!!}
		</td>
		<td>
			<a href="{{URL::to('/Lavado')}}" class="btn btn-success">Regresar</a>
		</td>
	<table>
	
	
@endsection

resources/views/lavado/edit.blade.php
@extends('layouts.admin')
@section('content')
@include('alerts.request')

	<br>
	<div>
		{!!Form::model($lavados,['route'=>['Lavado.update',$lavados],'method'=>'PUT'])!!}	
			@include('lavado.forms.lav')
	</div>
	<div class="cuadro">
	<table style="  border-collapse: separate;
 	 border-spacing: 10px 5px">
		
		<td>
			{!!Form::submit('Actualizar',['class'=>'btn btn-info'])!!}
			{!!Form::close()!!}
		</td>
		<td>
		<a href="{{URL::to('/Lavado')}}" class="btn btn-success">Regresar</a>
		</td>
		
		<!--td>
			{!!Form::open(['route'=>['Lavado.destroy', $lavados], 'method' => 'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
			{!!Form::close()!!}

		</td>-->
	</table>
	@endsection	

resources/views/lavado/index.blade.php
@extends('layouts.admin')

@include('alerts.success')

	@section('content')
	<table class="table">
		<thead>
			<th>ID</th>
			<th>TIPO</th>
			<th>COSTO</th>
			<th>FECHA INGRESO</th>
			<th>FECHA SALIDA</th>
			<th>TERMINADO</th>
			<th>LAVADOR</th>
			<th>ID VEHICULO</th>
			<!--<th>VER</th>-->
			<th>EDITAR</th>
			<th>ELIMINAR</th>

		</thead>
		@foreach($lavados as $lavado)
			<tbody>
				<td>{{$lavado->id}}</td>
				<td>{{$lavado->tipo}}</td>
				<td>{{$lavado->costo}}</td>
				<td>{{$lavado->fechaingreso}}</td>
				<td>{{$lavado->fechasalida}}</td>
				<td>{{$lavado->culminacion}}</td>
				<td>{{$lavado->user_id}}</td>
				<td>{{$lavado->vehiculo_id}}</td>
				{{-- 				<td>{{$lavado->lavadousername}}</td>
								<td>{{$lavado->lavadoplacavehiculo}}</td> --}}

				<!--<th>
				{!!link_to_route('Lavado.show', $title = 'VER', $parameters = $lavado->id, $attributes = ['class'=>'btn btn-info'])!!}
				</th>-->
				<th>
				{!!link_to_route('Lavado.edit', $title = 'EDITAR', $parameters = $lavado->id, $attributes = ['class'=>'btn btn-primary'])!!}
				</th>
				<td>
					{!!Form::open(['route'=>['Lavado.destroy', $lavado], 'method' => 'DELETE'])!!}
					{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
					{!!Form::close()!!}

				</td>
			</tbody>
		@endforeach
	</table>
	{!!$lavados->render()!!}

	@endsection