app/Http/routes.php
<?php

Route::resource('Usuario','UsuarioController');
Route::resource('Cliente','ClienteController');
Route::Controller("Cliente","ClienteController");
Route::resource('Vehiculo','VehiculoController');
Route::resource('Lavado','LavadoController');
Route::resource('Comprobante','ComprobanteController');
Route::resource('log','LogController');
Route::get('logout','LogController@logout');
Route::resource('Buscar','GananciaController');
Route::resource('MejorLavador','MejorLavadorController');
Route::resource('MejorAuto','AutoController');

////Route::post('/Cliente/show', 'ClienteController@store');

Route::Controller("/Cliente","ClienteController");
Route::Controller("/Usuario","UsuarioController");









/**ESTO SON DEL MENU QUE NOS EMPEZARA A MOSTRAR ¨*/
Route::get('/','FrontController@index');
Route::get('contacto','FrontController@contacto');
Route::get('reviews','FrontController@reviews');


Route::get('admin','FrontController@admin');
Route:: get('index','FrontController@index');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');*/

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Vehiculo.php
<?php namespace CarWash;

use Illuminate\Database\Eloquent\Model;

class Vehiculo extends Model {

	public $table = "vehiculos";
	protected $fillable = ['propietario','placa', 'marca', 'modelo','color'];


	//Relacion  con lavados
	public function lavados(){
			return $this->hasMany('CarWash\Lavado');
			//return $this->hasMany('Lavado::class');
	}
}

app/Http/Controllers/VehiculoController.php
<?php namespace CarWash\Http\Controllers;

use CarWash\Http\Requests;
use CarWash\Http\Requests\VehiculoCreateRequest;
use CarWash\Http\Requests\VehiculoUpdateRequest;
use CarWash\Http\Controllers\Controller;
use CarWash\Vehiculo;
use CarWash\Lavado;
use Session;
use Redirect;
use Illuminate\Routing\Route;
use Illuminate\Http\Request;

class VehiculoController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$vehiculos = Vehiculo::paginate(5);
          //envia infrmacion con compact
        return view('vehiculo.index',compact('vehiculos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('vehiculo.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(VehiculoCreateRequest $request)
	{
		Vehiculo::create([
			'propietario' => $request['propietario'],
            'placa' => $request['placa'],
            'marca' => $request['marca'],
            'modelo' => $request['modelo'],
            'color' => $request['color'],
         ]);
        return redirect('/Vehiculo')->with('message', 'Vehiculo Creado Correctamente');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$vehiculo =Vehiculo::find($id);
        return view('vehiculo.edit',['vehiculo'=>$vehiculo]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(VehiculoUpdateRequest $request, $id)
	{
		$vehiculo =Vehiculo::find($id);
        $vehiculo->fill($request->all());
        $vehiculo->save();
        Session::flash('message','Vehiculo Actualizado Correctamente');
        return Redirect::to('/Vehiculo');

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$vehiculo =Vehiculo::find($id);
        $vehiculo->delete();
        Session::flash('message','Vehiculo Eliminado Correctamente');
        return Redirect::to('/Vehiculo');
	}

}

resources/views/vehiculo/create.blade.php
@extends('layouts.admin')
	@section('content')
	@if(count($errors) > 0)
		<div class="alert alert-danger alert-dismissible" role="alert">
	  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  	<ul>
	  		@foreach($errors->all() as $error)
	  		<li>{!! $error !!}</li>
	  		@endforeach
	  	</ul>
		</div>
	@endif
	
		<div>
	{!!Form::open(['route'=>'Vehiculo.store', 'method'=>'POST'])!!}
			@include('vehiculo.forms.veh')
	</div>
	
	<div class="cuadro">
	<table style="  border-collapse: separate; border-spacing: 10px 5px">
		<td>
	{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
	{!!Form::close()!!}
		</td>
		<td>
			<a href="{{URL::to('/Vehiculo')}}" class="btn btn-success">Regresar</a>
		</td>
	<table>
		


	@endsection

resources/views/vehiculo/edit.blade.php
@extends('layouts.admin')
@section('content')
@include('alerts.request')
		
	<br>
	<div>
		{!!Form::model($vehiculo,['route'=>['Vehiculo.update',$vehiculo],'method'=>'PUT'])!!}
			@include('vehiculo.forms.veh')
	</div>
	<div class="cuadro">
	<table style="  border-collapse: separate;
 	 border-spacing: 10px 5px">
		
		<td>
			{!!Form::submit('Actualizar',['class'=>'btn btn-info'])!!}
			{!!Form::close()!!}
		</td>
		<td>
		<a href="{{URL::to('/Vehiculo')}}" class="btn btn-success">Regresar</a>
		</td>
		<!--<td>
			{!!Form::open(['route'=>['Vehiculo.destroy', $vehiculo], 'method' => 'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
			{!!Form::close()!!}

		</td>-->
	</table>
	@endsection

resources/views/vehiculo/index.blade.php
@extends('layouts.admin')


@include('alerts.success')

	@section('content')
	<table class="table">
		<thead>
			<th>ID</th>
			<th>PROPIEATRIO</th>
			<th>PLACA</th>
			<th>MARCA</th>
			<th>MODELO</th>
			<th>COLOR</th>
			<!--<th>VER</th>-->
			<th>EDITAR</th>
			<th>ELIMINAR</th>
		</thead>
	@foreach($vehiculos as $vehiculo)
			<tbody>
				<td>{{$vehiculo->id}}</td>
				<td>{{$vehiculo->propietario}}</td>
				<td>{{$vehiculo->placa}}</td>
				<td>{{$vehiculo->marca}}</td>
				<td>{{$vehiculo->modelo}}</td>
				<td>{{$vehiculo->color}}</td>
				<!--<td>
			{!!link_to_route('Vehiculo.show', $title = 'VER', $parameters = $vehiculo->id, $attributes = ['class'=>'btn btn-info'])!!}
				</td>-->
				<td>
			{!!link_to_route('Vehiculo.edit', $title = 'EDITAR', $parameters = $vehiculo->id, $attributes = ['class'=>'btn btn-primary'])!!}
				</td>
				
				<td>
			{!!Form::open(['route'=>['Vehiculo.destroy', $vehiculo], 'method' => 'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
			{!!Form::close()!!}

				</td>
			</tbody>
		@endforeach
	</table>
		{!!$vehiculos->render()!!}
	@endsection