app/Http/routes.php
<?php

Route::resource('Usuario','UsuarioController');
Route::resource('Cliente','ClienteController');
Route::Controller("Cliente","ClienteController");
Route::resource('Vehiculo','VehiculoController');
Route::resource('Lavado','LavadoController');
Route::resource('Comprobante','ComprobanteController');
Route::resource('log','LogController');
Route::get('logout','LogController@logout');
Route::resource('Buscar','GananciaController');
Route::resource('MejorLavador','MejorLavadorController');
Route::resource('MejorAuto','AutoController');

////Route::post('/Cliente/show', 'ClienteController@store');

Route::Controller("/Cliente","ClienteController");
Route::Controller("/Usuario","UsuarioController");









/**ESTO SON DEL MENU QUE NOS EMPEZARA A MOSTRAR ¨*/
Route::get('/','FrontController@index');
Route::get('contacto','FrontController@contacto');
Route::get('reviews','FrontController@reviews');


Route::get('admin','FrontController@admin');
Route:: get('index','FrontController@index');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');*/

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Cliente.php
<?php namespace CarWash;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model {

	public $table = "clientes";
	protected $fillable = ['dni', 'nombres', 'apellidos','sexo','telefono'];

}

app/Http/Controllers/ClienteController.php
<?php namespace CarWash\Http\Controllers;

use CarWash\Http\Requests;
use CarWash\Http\Requests\ClienteCreateRequest;
use CarWash\Http\Requests\ClienteUpdateRequest;
use CarWash\Http\Controllers\Controller;
use CarWash\Cliente;
use Session;
use Redirect;
use Illuminate\Routing\Route;
use Illuminate\Http\Request;

class ClienteController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$clientes = Cliente::paginate(10);
          //envia infrmacion con compact 
        return view('cliente.index',compact('clientes'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('cliente.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(ClienteCreateRequest $request)
	{
		Cliente::create([
            'dni' => $request['dni'],
            'nombres' => $request['nombres'],
            'apellidos' => $request['apellidos'],
            'sexo' => $request['sexo'],
            'telefono' => $request['telefono'],
         ]);
        return redirect('/Cliente')->with('message', 'Cliente Creado Correctamente');     
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//$cliente = Cliente::find($id);
		//return view('cliente.show',['cliente'=>$cliente]);
		//return view('cliente.show',['cliente'=>$cliente]);
		$cliente = Cliente::find($id);
        return View::make('cliente.show')->with('cliente', $cliente);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		  $cliente = Cliente::find($id);
          return view('clientes.edit',['cliente'=>$cliente]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(ClienteUpdateRequest $request, $id)
	{
		$cliente =Cliente::find($id);
        $cliente->fill($request->all());
        $cliente->save();
        Session::flash('message','Usuario Actualizado Correctamente');
        return Redirect::to('/Cliente');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$cliente =Cliente::find($id);
        $cliente->delete();
        Session::flash('message','Usuario Eliminado Correctamente');
        return Redirect::to('/Cliente'); 
	}

}

resources/views/cliente/create.blade.php
@extends('layouts.admin')
	@section('content')
	@if(count($errors) > 0)
		<div class="alert alert-danger alert-dismissible" role="alert">
	  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  	<ul>
	  		@foreach($errors->all() as $error)
	  		<li>{!! $error !!}</li>
	  		@endforeach
	  	</ul>
		</div>
	@endif
	
	<div>
	{!!Form::open(['route'=>'Cliente.store', 'method'=>'POST'])!!}
			@include('cliente.forms.cl')
	</div>
	
	<div class="cuadro">
	<table style="  border-collapse: separate; border-spacing: 10px 5px">
		<td>
			{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
			{!!Form::close()!!}
		</td>
		<td>
			<a href="{{URL::to('/Cliente')}}" class="btn btn-success">Regresar</a>
		</td>
	<table>
	@endsection

resources/views/cliente/edit.blade.php
@extends('layouts.admin')
@section('content')
@include('alerts.request')	
	<br>
	<div>
		{!!Form::model($cliente,['route'=>['Cliente.update',$cliente],'method'=>'PUT'])!!}
			@include('cliente.forms.cl')
	</div>
	<div class="cuadro">
	<table style="  border-collapse: separate; border-spacing: 10px 5px">
		<td>
			{!!Form::submit('Aceptar',['class'=>'btn btn-primary'])!!}
			{!!Form::close()!!}
		</td>
		
		<td>
		<a href="{{URL::to('/Cliente')}}" class="btn btn-success">Regresar</a>
		</td>

<!--		<td>
			{!!Form::open(['route'=>['Cliente.destroy', $cliente], 'method' => 'DELETE'])!!}
			{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
			{!!Form::close()!!}

		</td>	-->
	</table>
	@endsection

resources/views/cliente/index.blade.php
@extends('layouts.admin')

@include('alerts.success')

	@section('content')
	<table class="table">
		<thead>
			<th>ID</th>
			<th>Dni</th>
			<th>Nombres</th>
			<th>Email</th>
			<th>Sexo</th>
			<th>Telefono</th>
			<!--<th>Ver</th>-->
			<th>EDITAR</th>
			<th>ELIMINAR</th>
		</thead>
		@foreach($clientes as $cliente)
			<tbody>
				<td>{{$cliente->id}}</td>
				<td>{{$cliente->dni}}</td>
				<td>{{$cliente->nombres}}</td>
				<td>{{$cliente->apellidos}}</td>
				<td>{{$cliente->sexo}}</td>
				<td>{{$cliente->telefono}}</td>
				<!--<td>
				{{ link_to('cliente'.$cliente->id, 'Ver') }}
				{!!link_to_route('Cliente.show', $title = 'Ver', $parameters = $cliente->id, $attributes = ['class'=>'btn btn-info'])!!}
				<a href="cliente/show/{{ $cliente->id}}" class="btn btn-info"> Ver</a>
				</td>-->
				<td>
				{!!link_to_route('Cliente.edit', $title = 'Editar', $parameters = $cliente->id, $attributes = ['class'=>'btn btn-primary'])!!}

				</td>
				<td>
					{!!Form::open(['route'=>['Cliente.destroy', $cliente], 'method' => 'DELETE'])!!}
					{!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
				</td>
			</tbody>
		@endforeach
	</table>
	{!!$clientes->render()!!}
	@endsection

resources/views/cliente/show.blade.php
@extends('layouts.admin')
	@section('content')
	
	<table class="table">
		<thead>
			<th>ID</th>
			<th>Dni</th>
			<th>Nombres</th>
			<th>Email</th>
			<th>Sexo</th>
			<th>Telefono</th>
		</thead>
		@foreach($clientes as $cliente)
			<tbody>
				<td>{{$cliente->id}}</td>
				<td>{{$cliente->dni}}</td>
				<td>{{$cliente->nombres}}</td>
				<td>{{$cliente->apellidos}}</td>
				<td>{{$cliente->sexo}}</td>
				<td>{{$cliente->telefono}}</td>
				<td>
                    <a href="{{URL::to('/Cliente')}}" class="btn btn-default">Regresar</a>
				</td>
				
			</tbody>
		@endforeach
	</table>

	@endsection